" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Plug 'ctrlpvim/ctrlp.vim'
Plug 'ycm-core/YouCompleteMe'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/vim-easy-align'
Plug 'Yggdroot/indentLine'
Plug 'airblade/vim-gitgutter'
" Plug 'jiangmiao/auto-pairs'
Plug 'mileszs/ack.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'majutsushi/tagbar'
Plug 'godlygeek/tabular'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'preservim/nerdcommenter'
Plug 'junegunn/fzf', { 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Initialize plugin system
call plug#end()
set encoding=utf-8
let mapleader = ','
source ~/.vim/autoload/cscope_maps.vim
set termguicolors
set background=dark
colorscheme gruvbox

" Keys mapping
map <C-n> :NERDTreeToggle $HOME<CR>
map <C-j> :call WinMove('j')<CR>
map <C-k> :call WinMove('k')<CR>
map <C-h> :call WinMove('h')<CR>
map <C-l> :call WinMove('l')<CR>
nnoremap <F5> :buffers<CR>:buffer<Space> 
noremap <F9> :tabs<CR>:tabn<Space> 
nnoremap <Leader>f :NERDTreeFind<CR>
nnoremap <F8> :TagbarToggle<CR>
nnoremap <F2> :noh<CR>
nnoremap / /\v
nnoremap ; :Buffers<CR>
nnoremap <Leader>t :Files<CR>
nnoremap <Leader>r :Tags<CR>
nnoremap <Leader>x :cclose<CR>
" Sets
syntax on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set lcs+=space:·
set lcs+=eol:\^
set lcs+=tab:>-
set list
set fillchars+=vert:\|
set hlsearch
set incsearch
set smartindent
set fdm=syntax
set nofoldenable
set t_Co=256
set autowrite
set hidden
set ignorecase
set smartcase
set directory^=$HOME/.vim/tmp//

" Global vars
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
" unicode symbols
let g:airline_symbols.linenr = 'Ξ'
let g:airline_symbols.whitespace = 'Ξ'

let g:airline_theme='dark'
let g:airline#extensions#tabline#enabled = 1
let g:NERDTreeWinSize=40
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'wrc'
let g:ctrlp_root_markers = ['.gitignore']
let g:ycm_global_ycm_extra_conf = "$HOME/.ycm_extra_conf.py"
let g:indentLine_leadingSpaceChar='·'

" Buffergator
let g:buffergator_viewport_split_policy="B"
let g:buffergator_suppress_keymaps=1
nnoremap <Leader>b :BuffergatorOpen<CR>
nnoremap <Leader>B :BuffergatorClose<CR>
nnoremap <Leader>to :BuffergatorTabsOpen<CR>
nnoremap <Leader>tc :BuffergatorTabsClose<CR>

" Ack.vim"
let g:ackprg = 'ag --nogroup --nocolor --column'
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>
nnoremap <Leader>aw :Ack! "\b<cword>\b" <CR>

function! WinMove(key)
    let t:curwin = winnr()
    exec "wincmd ".a:key
    if (t:curwin == winnr())
        if (match(a:key,'[jk]'))
            wincmd v
        else
            wincmd s
        endif
        exec "wincmd ".a:key
    endif
endfunction

function! BufSel(pattern)
    let bufcount = bufnr("$")
    let currbufnr = 1
    let nummatches = 0
    let firstmatchingbufnr = 0
    while currbufnr <= bufcount
        if(bufexists(currbufnr))
            let currbufname = bufname(currbufnr)
            if(match(currbufname, a:pattern) > -1)
                echo currbufnr . ": ". bufname(currbufnr)
                let nummatches += 1
                let firstmatchingbufnr = currbufnr
            endif
        endif
        let currbufnr = currbufnr + 1
    endwhile
    if(nummatches == 1)
        execute ":buffer ". firstmatchingbufnr
    elseif(nummatches > 1)
        let desiredbufnr = input("Enter buffer number: ")
        if(strlen(desiredbufnr) != 0)
            execute ":buffer ". desiredbufnr
        endif
    else
        echo "No matching buffers"
    endif
endfunction

