require("plugins")
require("lsp")
require("treesitter")
require("mytelescope")
require("mystatusline")
require("mycscope_maps")
-- require("myminisurround")
-- require("mygitsigns")
-- require("mycmp")
-- require("myrosepine")

